services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
     - db

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${POSTGRES_DATA}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - dbvolume:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  dbvolume:
